import {Ingredient} from "./";

export const INGREDIENTS: Ingredient[] = [
  {
    id: 1,
    type: "Medallon",
    name: "Medallón carne 110gr",
    additionalPrice: 2000,
    minQuantity: 1,
    maxQuantity: 5,
    selectable: true,
  },
  {
    id: 2,
    type: "Medallon",
    name: "Medallón carne 150gr",
    additionalPrice: 3000,
    minQuantity: 1,
    maxQuantity: 4,
    selectable: false,
  },
  {
    id: 3,
    type: "Topping",
    name: "Cheddar",
    additionalPrice: 500,
    minQuantity: 0,
    maxQuantity: 8,
    selectable: false,
  },
  {
    id: 4,
    type: "Topping",
    name: "Bacon",
    additionalPrice: 700,
    minQuantity: 0,
    maxQuantity: 4,
    selectable: false,
  },
  {
    id: 5,
    type: "Topping",
    name: "Cheddar fundido",
    additionalPrice: 1200,
    minQuantity: 0,
    maxQuantity: 1,
    selectable: false,
  },
  {
    id: 6,
    type: "Topping",
    name: "Cebolla cryspy",
    additionalPrice: 500,
    minQuantity: 0,
    maxQuantity: 1,
    selectable: false,
  },
  {
    id: 6,
    type: "Topping",
    name: "Cebolla cryspy",
    additionalPrice: 500,
    minQuantity: 0,
    maxQuantity: 1,
    selectable: false,
  },
  {
    id: 7,
    type: "Topping",
    name: "Verdeo",
    additionalPrice: 700,
    minQuantity: 0,
    maxQuantity: 1,
    selectable: false,
  },
  {
    id: 8,
    type: "Pan",
    name: "Pan de papa",
    additionalPrice: undefined,
    minQuantity: 1,
    maxQuantity: 1,
    selectable: true,
  },
  {
    id: 9,
    type: "Pan",
    name: "Pan de queso",
    additionalPrice: undefined,
    minQuantity: 1,
    maxQuantity: 1,
    selectable: true,
  },
  {
    id: 10,
    type: "Medallon",
    name: "Medallón NotCo",
    additionalPrice: 2500,
    minQuantity: 1,
    maxQuantity: 3,
    selectable: true,
  },
  {
    id: 11,
    type: "Medallon",
    name: "Medallón pollo",
    additionalPrice: 1500,
    minQuantity: 1,
    maxQuantity: 5,
    selectable: true,
  },
];
